# Adds namespace to all resources.
namespace: kueue-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: kueue-

labels:
- includeTemplates: true
  pairs:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
- includeSelectors: true
  pairs:
    control-plane: controller-manager

# [METRICS] Expose the controller manager metrics service.
resources:
- ../components/crd
- ../components/rbac
- ../components/manager-ocp
- ../components/visibility
- ../components/webhook
- ../components/certmanager
- metrics_service.yaml

# Sets the namespace for the role binding as kube-system instead of default kueue-system
transformers:
- role_binding_visibility_transformer.yaml

# Mount the controller config file for loading manager configurations
# through a ComponentConfig type

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml

# Expose port used by the visibility server

# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
# Uncomment 'CERTMANAGER' sections in crd/kustomization.yaml to enable the CA injection in the admission webhooks.
# 'CERTMANAGER' needs to be enabled to use ca injection
patches:
- path: manager_config_patch.yaml
- path: manager_webhook_patch.yaml
- path: manager_visibility_patch.yaml
- path: mutating_webhookcainjection_patch.yaml
- path: validating_webhookcainjection_patch.yaml


# the following config is for teaching kustomize how to do var substitution
#[CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER' prefix.
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: CERTIFICATE_NAMESPACE
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref: {}
  name: CERTIFICATE_NAME
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref:
    fieldPath: metadata.namespace
  name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: webhook-service
    version: v1
- fieldref: {}
  name: SERVICE_NAME
  objref:
    kind: Service
    name: webhook-service
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
